### PR TITLE
Food model added for hacktoberfest

### PR DESCRIPTION
**Pull request by felipedferreira**
as per #11 I have created the following PR. please let me know what you think.

### CODE REVIEW

**Comment by UncleFifi** [comment]
Would you mind letting know if there are any issues on this code please?

**Comment by alator21** [comment]
Hello @UncleFifi . I'm kinda busy these days so i'm gonna review it later. Thanks for the contribution

**Comment by UncleFifi** [comment]
@alator21 Would you kindly review my changes as this is the last PR I need to complete Hacktoberfest

**Comment by alator21** [comment]
Hello @UncleFifi . I already added the `hacktoberfest-accepted` tag. Are you sure it's not counting towards hacktoberfest?

**Pull request closed without merging**
